//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NorthwindEntities : DbContext
    {
        public NorthwindEntities()
            : base("name=NorthwindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    
        public virtual ObjectResult<ProductosDescontinuados_Result> ProductosDescontinuados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductosDescontinuados_Result>("ProductosDescontinuados");
        }
    
        public virtual ObjectResult<ProductosCategorias_Result> ProductosCategorias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductosCategorias_Result>("ProductosCategorias");
        }
    
        public virtual ObjectResult<Reporting_Result> Reporting(string orderDate)
        {
            var orderDateParameter = orderDate != null ?
                new ObjectParameter("OrderDate", orderDate) :
                new ObjectParameter("OrderDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reporting_Result>("Reporting", orderDateParameter);
        }
    }
}
